import { Resend } from "resend";
// @ts-ignore — markdown-it might not have types
import { marked } from "./markdown.js";

const resend = new Resend(process.env.RESEND_API_KEY);

const FROM_EMAIL = process.env.FROM_EMAIL || "Zvoon <noreply@zvoon.me>";

function buildHtmlEmail(
  summaryMarkdown: string,
  roomSlug: string,
  date: string,
  participantNames: string[],
  lang: string
): string {
  const summaryHtml = markdownToHtml(summaryMarkdown);
  const isEn = lang === "en";

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:20px;">
    <div style="background:#0a0a0a;border-radius:16px;overflow:hidden;">
      <!-- Header -->
      <div style="padding:24px 28px;border-bottom:1px solid #222;">
        <div style="display:flex;align-items:center;gap:10px;">
          <span style="font-size:22px;font-weight:800;color:#f5f5f5;">Zvoon</span>
        </div>
        <div style="margin-top:8px;color:#888;font-size:14px;">
          ${isEn ? "Call Summary" : "Сводка звонка"} · ${date}
        </div>
      </div>
      <!-- Body -->
      <div style="padding:28px;color:#e5e5e5;font-size:15px;line-height:1.7;">
        ${summaryHtml}
      </div>
      <!-- Footer -->
      <div style="padding:20px 28px;border-top:1px solid #222;color:#666;font-size:12px;">
        ${isEn
          ? "This summary was generated by AI based on the call recording. It may contain inaccuracies."
          : "Эта сводка сгенерирована ИИ на основе записи звонка. Может содержать неточности."}
        <br><br>
        <a href="https://zvoon.me" style="color:#e8734a;text-decoration:none;">zvoon.me</a>
      </div>
    </div>
  </div>
</body>
</html>`;
}

/**
 * Simple markdown to HTML (no external dependency).
 */
function markdownToHtml(md: string): string {
  return md
    // Headers
    .replace(/^### (.+)$/gm, '<h3 style="color:#f5f5f5;font-size:16px;margin:20px 0 8px;">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="color:#f5f5f5;font-size:18px;margin:24px 0 12px;">$1</h2>')
    // Checkboxes
    .replace(/^- \[ \] (.+)$/gm, '<div style="margin:4px 0;padding-left:8px;">☐ $1</div>')
    .replace(/^- \[x\] (.+)$/gm, '<div style="margin:4px 0;padding-left:8px;">☑ $1</div>')
    // Bullet lists
    .replace(/^- (.+)$/gm, '<div style="margin:4px 0;padding-left:8px;">• $1</div>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong style="color:#f5f5f5;">$1</strong>')
    // Italic
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Paragraphs (double newline)
    .replace(/\n\n/g, '<br><br>')
    // Single newlines
    .replace(/\n/g, '<br>');
}

/**
 * Send summary email to a participant.
 */
export async function sendSummaryEmail(
  to: string,
  summary: string,
  roomSlug: string,
  participantNames: string[],
  lang: string = "ru"
): Promise<void> {
  const date = new Date().toLocaleDateString(lang === "en" ? "en-US" : "ru-RU", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const isEn = lang === "en";
  const subject = isEn
    ? `Call Summary — ${date}`
    : `Сводка звонка — ${date}`;

  const html = buildHtmlEmail(summary, roomSlug, date, participantNames, lang);

  try {
    const result = await resend.emails.send({
      from: FROM_EMAIL,
      to,
      subject,
      html,
    });
    console.log(`Summary email sent to ${to}:`, result);
  } catch (e) {
    console.error(`Failed to send email to ${to}:`, e);
    throw e;
  }
}

/**
 * Send error notification when summary generation fails.
 */
export async function sendErrorEmail(
  to: string,
  lang: string = "ru"
): Promise<void> {
  const isEn = lang === "en";

  await resend.emails.send({
    from: FROM_EMAIL,
    to,
    subject: isEn ? "Call Summary — Error" : "Сводка звонка — Ошибка",
    html: `<div style="font-family:sans-serif;padding:20px;">
      <h2>${isEn ? "Sorry, we couldn't generate the summary" : "Извините, не удалось создать сводку"}</h2>
      <p>${isEn
        ? "There was a technical issue processing your call recording. Please try again next time."
        : "Произошла техническая ошибка при обработке записи звонка. Попробуйте в следующий раз."
      }</p>
      <p style="color:#888;font-size:12px;margin-top:20px;">
        <a href="https://zvoon.me" style="color:#e8734a;">zvoon.me</a>
      </p>
    </div>`,
  });
}
